---
title: "14_mem"
author: "Lachlan Dryburgh"
date: "2024-06-13"
output: html_document
---

```{r}
library(Seurat)

seu3 <- readRDS('../output/refiltered.rds')
```


```{r}
DimPlot(seu3)

seu_mem <- subset(seu3, subset = seurat_clusters %in% c(0,1))

DimPlot(seu_mem, split.by = 'diet')
```

```{r}
seu_mem <- NormalizeData(seu_mem)
seu_mem <- FindVariableFeatures(seu_mem)
seu_mem <- ScaleData(seu_mem)

seu_mem <- RunPCA(seu_mem)

DimPlot(seu_mem, reduction = 'pca', split.by = 'diet')

seu_mem <- RunUMAP(seu_mem, dims = 1:10)

DimPlot(seu_mem, reduction = 'umap', split.by = 'diet')

FeaturePlot(seu_mem, features = 'Pdcd1')
```

```{r}
seu_mem <- FindNeighbors(seu_mem, dims = 1:5)
seu_mem <- FindClusters(seu_mem, resolution =  0.3)

DimPlot(seu_mem, group.by = 'seurat_clusters')
```
```{r}
pc1 <- seu_mem@reductions$pca@feature.loadings[,1]



FeaturePlot(seu_mem, features = "Gzmm", split.by = 'diet')
FeaturePlot(seu_mem, features = "Slamf6", split.by = 'diet')
FeaturePlot(seu_mem, features = "Ccl5", split.by = 'diet')
FeaturePlot(seu_mem, features = "Dapl1", split.by = 'diet')
FeaturePlot(seu_mem, features = "Klra7", split.by = 'diet')
FeaturePlot(seu_mem, features = "S100a6", split.by = 'diet')
FeaturePlot(seu_mem, features = "Ctla2a", split.by = 'diet')
FeaturePlot(seu_mem, features = "Ccr5", split.by = 'diet')


FeaturePlot(seu3, features = "Gzmm")
FeaturePlot(seu3, features = "Slamf6")
FeaturePlot(seu3, features = "Ccl5")
FeaturePlot(seu3, features = "Dapl1")
FeaturePlot(seu3, features = "Klra7")
FeaturePlot(seu3, features = "S100a6")
FeaturePlot(seu3, features = "Ctla2a")
FeaturePlot(seu3, features = "Ccr5")

m <- FindMarkers(seu_mem, ident.1 = 0)
```

```{r}
hl <- colnames(subset(seu_mem, subset = seurat_clusters == 0))

DimPlot(seu3, cells.highlight = hl)
```

