---
title: "Composition Analysis"
author: "Lachlan Dryburgh"
date: "2024-02-27"
output: html_document
---

```{r}
library(Seurat)
library(ggplot2)
library(viridis)
seu2 <- readRDS('../output/reclustered.rds')
```

```{r}
df <- seu2@meta.data

DimPlot(seu2, group.by = 'clusters_res0.4')

ggplot(df, aes(x = group, fill = clusters_res0.4)) +
  geom_bar(position = "fill") +
  scale_y_continuous(labels = scales::percent)
```
```{r}
df <- seu2@meta.data

DimPlot(seu2, group.by = 'clusters_res0.5', split.by = 'group') + scale_color_viridis(discrete=TRUE, option="turbo")


ggplot(df, aes(x = group, fill = clusters_res0.5)) +
  geom_bar(position = "fill") +
  scale_fill_viridis_d(option = 'turbo')
```
```{r}
DimPlot(seu2, group.by = 'clusters_res0.7') + scale_color_viridis(discrete=TRUE, option="turbo")


ggplot(df, aes(x = group, fill = clusters_res0.7)) +
  geom_bar(position = "fill") +
  scale_fill_viridis_d(option = 'turbo')
```
```{r}
cell_count <- ncol(seu2)

set.seed(632024)
subs <- sample(1:3, cell_count, replace = T)


seu2$sample <- as.factor(paste(seu2$group, subs,  sep = '_'))

df <- seu2@meta.data

ggplot(df, aes(x = sample, fill = clusters_res0.5 )) +
  geom_bar(position = "fill", group = 'group') +
  scale_fill_viridis_d(option = 'turbo')
```
```{r}
library(speckle)


seu2 <- SetIdent(seu2, value = 'clusters_res0.5')
prop <- propeller(x = seu2)


props <- getTransformedProps(seu2$clusters_res0.5, seu2$sample, transform="logit")


barplot(props$Proportions, legend=TRUE, 
        ylab="Proportions")

plotCellTypeMeanVar(props$Counts)

prop
```
```{r}
write.csv(prop, '../output/proportions_analysis.csv')
```

